### ISSUE TITLE
More Information

### ISSUE THREAD

**Issue by crazyzxd** [fangchangma/self-supervised-depth-completion#1]
Hi, i m curious about your work. i have already read your paper . Is there anything new?
When  will you update the repository?

**Comment by crazyzxd** [comment]
Thanks.
Looking forward to it.

**Comment by fangchangma** [comment]
Quick update: I might have to push back the code release, hopefully by mid-October..

**Comment by SebasRatz** [comment]
Hi, I am also interested in your work! Looking forward to the code being released

**Comment by zhby99** [comment]
> Hi, I am also interested in your work! Looking forward to the code being released

same here, looking forward to the code!

**Comment by zouhongwei** [comment]
Hi, I am also interested in your work! Looking forward to the code being released

**Comment by LingerWang** [comment]
Another looking forward to your updating

**Comment by Xiangjun-Gao** [comment]
Looking forward to releasing you code soon

**Comment by Usernamezhx** [comment]
Looking forward to releasing you code soon

**Comment by ialhashim** [comment]
Any update on the code?

**Comment by Hansry** [comment]
Ｈello, any update on the code?

**Comment by fangchangma** [comment]
The network definition and a trained model has been released. I'll put out the complete code and the other trained models later.

**Comment by wuheng199112068** [comment]
An error occurred when entering such a parameter on the command line，what can we input about [checkpoint -path]？Can you give us an example? Thank you

Namespace(batch_size=1, criterion='l2', epochs=11, evaluate='[checkpoint-path]', i
nput='gd', jitter=0.1, layers=34, lr=1e-05, pretrained=False, print_freq=10, rank_metric='rmse', result='..\results', resume='', start_epoch=0, train_mode='dense', use_d=True, use_g=True, use_pose=False, use_rgb=False, val='select', w1=0, w2=0, weight_decay=0, workers=4)
=> no model found at '[checkpoint-path]'
