### ISSUE TITLE
Error when import the pre-train model

### ISSUE THREAD

**Issue by AbnerCSZ** [fangchangma/self-supervised-depth-completion#10]
I download the model trained with semi-dense lidar ground truth, from:[supervised model](http://datasets.lids.mit.edu/self-supervised-depth-completion/supervised/).

When I run

```
torch.load('supervised/model_best.pth.tar')
```

This is a error:
```
Traceback (most recent call last):
  File "model.py", line 173, in <module>
    main()
  File "model.py", line 164, in main
    torch.load('supervised/model_best.pth.tar')
  File "/home/S/.local/lib/python3.5/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/S/.local/lib/python3.5/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
ImportError: No module named 'metrics'
```
Could your tell me why?
Thanks~

**Comment by fangchangma** [comment]
Hi. That's probably because I haven't uploaded the metrics.py file (didn't realize this was also necessary). I will upload the rest of the source code today.

**Comment by AbnerCSZ** [comment]
Thanks for your help. I can load model after updating.

**Comment by wuheng199112068** [comment]
An error occurred when entering such a parameter on the command line，what can we input about [checkpoint -path]？Can you give us an example?

Namespace(batch_size=1, criterion='l2', epochs=11, evaluate='[checkpoint-path]', i
nput='gd', jitter=0.1, layers=34, lr=1e-05, pretrained=False, print_freq=10, rank_metric='rmse', result='..\results', resume='', start_epoch=0, train_mode='dense', use_d=True, use_g=True, use_pose=False, use_rgb=False, val='select', w1=0, w2=0, weight_decay=0, workers=4)
=> no model found at '[checkpoint-path]'
