### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by wangyingyu** [fangchangma/self-supervised-depth-completion#18]
Hello, 
This is a great project, I am very interested in it, but I found that there is no data set that can be used directly. Can you share it? 
Thank you

**Comment by xskyz** [comment]
@wangyingyu Hello, I want to know how to download the kitti depth dataset. I can't download it in the ' http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion'. Can you help me?
Thank you!

**Comment by wangyingyu** [comment]
> @wangyingyu @fangchangma Hello, I want to know how to download the kitti depth dataset. I can't download it in the ' http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion'. Can you help me?
> Thank you!
First, you need to download the annotated depth map dataset at this URL, and then you need to download the corresponding kitti rgb dataset. This is a tedious job, I have not completed it yet.@xskyz

**Comment by xskyz** [comment]
@wangyingyu Thank you for your prompt reply！

**Comment by wangyingyu** [comment]
@xskyz If you have a complete dataset or have some progress, you can share it. Thank you.

**Comment by xskyz** [comment]
@wangyingyu OK~ I will share it if I have some progress.

**Comment by fangchangma** [comment]
I just updated scripts for downloading the corresponding RGB images for KITTI Depth. Please let me know if you have any other questions.

**Comment by xskyz** [comment]
@fangchangma Thank you for your download scripts. But I got an unknown error when I used 'tar -xvf model_best.pth.tar ' to get  your pre-trained model. Can you help me?
On the other hand, can you give specific commands for training and testing?

**Comment by fangchangma** [comment]
@xskyz There is no need to decompress the `.tar` file --- that is just the postfix for Pytorch's checkpoints, not a real compressed file. Please load the `.tar` file directly using the commands in README.

**Comment by xskyz** [comment]
@fangchangma Thank you, and in addition, I want to know how to use your model to inpaint a specific depth map，can you give an example command?

**Comment by wangyingyu** [comment]
@fangchangma Thank you for your reply. I saw that you updated the val_select_crop_reg.py file. I want to know what the function of this file is. Also, which folder does it need to be placed in?
