### ISSUE TITLE
Data augmentation and normalization

### ISSUE THREAD

**Issue by daniel-pp** [fangchangma/self-supervised-depth-completion#2]
Your paper is really interesting, and I have tried implementing the network following your descriptions there. 

For the supervised network, I was wondering if you have used any data augmentation during training. If so, what kind? Also, do you normalize the depths in any way (both the input and the ground truth)?

**Comment by fangchangma** [comment]
We found data augmentation not to help much, and you can always start without data augmentation. The network should be able to learn well, both with and without depth normalization.

**Comment by daniel-pp** [comment]
Great, thanks for the prompt reply!
