### ISSUE TITLE
Creating the data folder structure

### ISSUE THREAD

**Issue by swapnesh-wani** [fangchangma/self-supervised-depth-completion#21]
@fangchangma I have two questions

1. I downloaded the kitii dataset which has a folder structure like this

![image](https://user-images.githubusercontent.com/32718761/56169705-0175f780-5fad-11e9-9497-0b68d9d6c3f1.png)

Now, do I have to delete |-- val folder and replace with the following?

![image](https://user-images.githubusercontent.com/32718761/56169757-2bc7b500-5fad-11e9-892f-bd0c3fad797a.png)

if my assumption is correct then the above steps will make dir structure like this

![image](https://user-images.githubusercontent.com/32718761/56169832-66c9e880-5fad-11e9-89f0-f43ecca31f78.png)

2. Where can I get the kitti_rgb data? Do I need to download from [here](http://www.cvlibs.net/datasets/kitti/raw_data.php) for all the drive data that is there is kitti depth dataset? If yes, then do I need to copy the same folder
![image](https://user-images.githubusercontent.com/32718761/56169757-2bc7b500-5fad-11e9-892f-bd0c3fad797a.png) again?

**Comment by fangchangma** [comment]
1. There is no need to delete or move any files from the kitti depth dataset. You can keep the raw `val` folder while having the `val_selection_cropped` folder in the same directory.
2. Yes, we need to download the raw data. and extract the rgb images. The rgb images need to be structured in a similar way to the depth dataset. 

The reason why I did not release the downloaded rgb dataset was to avoid violation of the kitti' licences.

**Comment by swapnesh-wani** [comment]
@fangchangma  thank you for your reply. Creating the rgb dataset is one tedious task because I have to look for each drive id and download the data and then selecting the corresponding images that are there in the depth-dataset. 

Just for the confirmation, after downloading all the relevant rgb files, the dir structure should look like this?

![image](https://user-images.githubusercontent.com/32718761/56174563-0cd31e00-5fc1-11e9-8467-4f5fffb1e1f3.png)

**Comment by wangyingyu** [comment]
> @fangchangma thank you for your reply. Creating the rgb dataset is one tedious task because I have to look for each drive id and download the data and then selecting the corresponding images that are there in the depth-dataset.
> 
> Just for the confirmation, after downloading all the relevant rgb files, the dir structure should look like this?
> 
> ![image](https://user-images.githubusercontent.com/32718761/56174563-0cd31e00-5fc1-11e9-8467-4f5fffb1e1f3.png)

Hello,
I have the same problem, and I don't know how to match rgb and d in the flower structure. Can you give me some advice?
Thank you.

**Comment by swapnesh-wani** [comment]
> > @fangchangma thank you for your reply. Creating the rgb dataset is one tedious task because I have to look for each drive id and download the data and then selecting the corresponding images that are there in the depth-dataset.
> > Just for the confirmation, after downloading all the relevant rgb files, the dir structure should look like this?
> > ![image](https://user-images.githubusercontent.com/32718761/56174563-0cd31e00-5fc1-11e9-8467-4f5fffb1e1f3.png)
> 
> Hello,
> I have the same problem, and I don't know how to match rgb and d in the flower structure. Can you give me some advice?
> Thank you.@swapnesh-wani

Hi @wangyingyu, I haven't downloaded the rgb dataset yet. But, I think the rgb dataset should look like my previous comment. Waiting for @fangchangma to confirm.

**Comment by fangchangma** [comment]
Hi. I just uploaded the scripts for downloading the RGB dataset. The README has also been updated to provide more details regarding the folder structures. Please let me know if it is unclear.

**Comment by swapnesh-wani** [comment]
@fangchangma  thanks for uploading the scripts. That will surely help a lot.

**Comment by wangyingyu** [comment]
@swapnesh-wani @fangchangma Thank you for your reply. But I still have a few questions about the datasets.
1)Is the val_selection_cropped folder in the kitti_depth folder downloaded from the manually selected validation and test data sets (5 GB) in [kitti depth](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion)?
2)The velodyne_raw folder in the /kitti_depth/train/20**_**_**_drive_****_sync/proj_depth/ folder is downloaded from [kitti depth](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion)'s projected raw LiDaR scans data set (2 GB) and placed In the corresponding position?

**Comment by fangchangma** [comment]
@wangyingyu 
1) Yes
2) Yes
