### ISSUE TITLE
Tools for estimating cam pose

### ISSUE THREAD

**Issue by skyhehe123** [fangchangma/self-supervised-depth-completion#3]
Hi,

Great work! I wonder which tools you are using for solving PnP /w RANSAC to estimate the camera pose.  Could please provide a snip-shot for these part of codes?

**Comment by fangchangma** [comment]
Hi. We use OpenCV.

**Comment by skyhehe123** [comment]
Thanks for quick reply.
I am still confused about estimating cam pose. Which API are you using? Could please show more details about it?
Great thanks!

**Comment by Usernamezhx** [comment]
@skyhehe123  sometimes it may look like this: [https://docs.opencv.org/3.4.3/dc/dbb/tutorial_py_calibration.html](url)

**Comment by skyhehe123** [comment]
@Usernamezhx thanks. I also find this one that maybe useful.
https://www.learnopencv.com/head-pose-estimation-using-opencv-and-dlib/
As mentioned in the paper, it is about 3D-2D pose estimation.

**Comment by fangchangma** [comment]
Indeed it is a pose estimation problem for 3D-2D pairs. We use cv2.solvePnPRansac
