### ISSUE TITLE
To much warning.

### ISSUE THREAD

**Issue by onionysy** [fangchangma/self-supervised-depth-completion#53]
When I training the net, the warning raise.
[W IndexingUtils.h:20] Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (function expandTensors)
Can you tell me how to fix it ?

**Comment by FrederikWarburg** [comment]
@onionysy did you fix this?

**Comment by FrederikWarburg** [comment]
I got rid of the warnings by changing line 55 in the criteria.py from

```
valid_mask = valid_mask.byte().detach()
```
to
```
valid_mask = valid_mask.bool().detach()
```
